SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://postgres:qwerty1234@localhost'
SECRET_KEY = 'qwerty1234'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = False
ADMIN_ROLE_ID = 1
MODER_ROLE_ID = 2
FLASK_APP='app.py'
FLASK_ENV='development'
FLASK_DEBUG=1