version: '3.3'

networks:
  net:

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: qwerty1234
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - ./papka

  flaskproj:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg2://post_user:qwerty1234@postgres-db:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    networks:
      - net
    command: bash -c "flask db init && flask db migate && flask db update && python unitest.py && flask run --host=0.0.0.0"
    volumes:
      - ./papka2

