version: '3.3'

networks:
  net:

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: qwerty1234
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - ./papka

  flyway:
    image: flyway/flyway
    environment:
      - "FLYWAY_CONNECT_RETRIES=10" # Увеличьте число повторных попыток подключения
    volumes:
      - /home/danila/downloads/database:/flyway/sql
    depends_on:
      - postgres-db
    command: ["-url=jdbc:postgresql://postgres-db:5432/postgres", "-user=post_user", "-password=qwerty1234", "migrate"]
    networks:
      - net

  flaskproj:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg2://post_user:qwerty1234@postgres-db:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
      - flyway
    networks:
      - net
    command: bash -c "python unitest.py && flask run --host=0.0.0.0"
    volumes:
      - /home/danila/downloads/Devops/papka2

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - net
